providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install --legacy-peer-deps"]

[variables]
NIXPACKS_NODE_VERSION = "22"
NPM_CONFIG_PRODUCTION = "false"
PUPPETEER_SKIP_DOWNLOAD = "true"
